###
GET  https://zeckysever.onrender.com/blog/allblog
Content-Type:  application/json

{
  "data":"649ff99ba3b7146985f744b6"
}

###
POST https://zeckysever.onrender.com/blog/detail
Content-Type:  application/json

{
  "slug":"higher-order-function-javascript"
}